### ISSUE TITLE
PUTASSET_TOKEN must be used

### ISSUE THREAD

**Issue by garronej** [coderaiser/node-putasset#3]
Good stuff but: 
``-tn, --token    : github token <https://github.com/settings/tokens/new>``
param does not work
PUTASSET_TOKEN env variable is the only way to get the CLI working.

Suggestion: Let override asset with same name.

Regards

**Comment by coderaiser** [comment]
That is strange, everything should [work as expected](https://github.com/coderaiser/node-putasset/blob/v4.0.1/bin/putasset.js#L70).

> Suggestion: Let override asset with same name.

That is a great idea for a pull request 🙂

**Comment by garronej** [comment]
Should indeed but does not :)
Look at the args: 
![image](https://user-images.githubusercontent.com/6702424/51289204-93e31b00-19ff-11e9-8663-d1ed3bc1b74f.png)

Fixed in the last PR
